### ISSUE TITLE
Add missing institutions to AR4

### ISSUE THREAD

**Issue by ipgray** [medea-project/ipcc-database#15]
Very few institutions N/A in AR4; try to track down manually the few that are N/A

**Comment by legaultpierre** [comment]
@ipgray I have updated the institutions but I need confirmations for some:
  - Daniel Murdiyarso (x2): what does the 'IPB' acronym stands for? Is this institution already in the db under another name?

  - Guilian Cambers: I have chosen the existing 'Australian Department of Arts, Sport, Environment...' institution: can you confirm it is the right choice? Also Guilian was referenced as a Puerto Rico author... do you have any clue why?

  - Raman Sukumar: I have chosen the 'Indian Institute of Science' instead of 'Indian Institute for Science' given

  - Roger B. Street: For the AR4 WG2 CHAP2 he had already an institution 'Tyndall Centre for Climate Change Research' but I have changed it anyway. 

  - Mohamed Salih: The only Erasmus Uni I've found on google is in Rotterdam and not in Sudan, so I guess there is a problem. I haven't done any modification here.

  - Shimon Awerbuch: I chose to assign him to 'University of Massachusetts' as 'University of Massachusetts, Lowell' does not exists

**Comment by ipgray** [comment]
@legaultpierre; nice work. i've flagged this, but it will have to wait till i get back. sounds like some of the choices you made are the right ones, but i'll have to explore a couple of the others.

**Comment by ipgray** [comment]
@legaultpierre:

> Daniel Maurdiyarso: IPB = Bogor Agricultural University
> Guilian Cambers: is an ERROR (properly in properly reproduced from the pdf file) ; it is Gillian Cambers; I cannot find her institution in the IPCC reports. She is currently in Australia, but she lived in the Caribbean for 25 years, and is marked as Puerto Rico in the IPCC report. Leave her as Puerto Rico and leave her institution N/A.
> Raman Sukumar: good choice
> Roger B. Street: for Street, I track his institution in AR4 WG2 CHAP2 as "University of Oxford", so that's a good change
> Mohamed Salih: this is a problem with our classifying, because he is indeed indentified in the IPCC documents as from Sudan, but looking at him online, he is at Erasmus University Rotterdam in the Hague. He seems like an individual that identified himself only by his nationality and not by the national affiliation of his institution. Perhaps we leave it "N/A" unless you have a way of combining the country-table with a new category Sudan-Erasmus University Rotterdam
> Shimon Awerbuch: That's cool

**Comment by legaultpierre** [comment]
Done
